# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#1. about"
  weight = 1

[[main]]
  name = "Perception and Cognition"
  url = "#2. bookSection"
  weight = 2

[[main]]
  name = "Visual Scale"
  url = "#5. scaleSection"
  weight = 3

[[main]]
  name = "Virtual Reality"
  url = "#10. vrSection"
  weight = 4



